[package]
name        = "halmasuit-spawn"
description = "Setuid-root privilege-drop helper for halmasuit. Microscopic, audited, no unsafe code."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[lints]
workspace = true

[dependencies]
