# tests/visual-phase-b-enc-shader.nix — Phase B golden-boot,
# encrypted-root LUKS × shader wallpaper. Epic #35 cell (enc, shader).
#
# Same end-to-end claim as visual-phase-b-enc-shader.nix, but the
# rootfs ITSELF is on a LUKS volume rather than a side data volume:
# halmasuit-luks's production wire unlocks /dev/vdb → switch_root
# mounts /dev/mapper/cryptroot as / → halmasuit's post-pivot chroot
# lands in the LUKS-rooted rootfs view.
#
# Dual-boot specialisation pattern (per
# nixpkgs/nixos/tests/systemd-initrd-luks-password.nix):
#   1. First boot — default config, no LUKS rootfs declared. Plain
#      qcow2 root. testScript luksFormats /dev/vdb, switches the
#      bootloader default to the `cryptroot` specialisation entry,
#      crashes.
#   2. Second boot — `cryptroot` specialisation activates:
#      `boot.initrd.luks.devices.cryptroot.device = "/dev/vdb"` +
#      `virtualisation.rootDevice = "/dev/mapper/cryptroot"` +
#      `autoFormat = true`. systemd-cryptsetup asks for the
#      passphrase; halmasuit-luks responds via the SAME wire as
#      side-volume; cryptroot unlocks; ext4 is auto-created;
#      multi-user.target reaches with `/` mounted from
#      /dev/mapper/cryptroot.

{
  system,
  nixpkgs,
  nix-config,
  halmasuit-debug,
  halmasuit-luks,
  halmasuit-session,
  halmasuit-vm-client,
  ssimulacra2-cli,
}:

let
  pkgs = import nixpkgs {
    inherit system;
    # niri-flake's niri-unstable may pull unfree deps transitively
    # (same rationale as visual-niri-session.nix).
    config.allowUnfree = true;
  };
in
pkgs.testers.runNixOSTest {
  name = "visual-phase-b-enc-shader";

  skipTypeCheck = true;

  interactive.nodes.machine = { ... }: {
    virtualisation.qemu.options = [
      "-device virtio-vga-gl"
      "-display gtk,gl=on"
    ];
  };

  nodes.machine = {
    imports = [
      ../nix/module.nix
      (import ./lib/phase-b-golden.nix {
        wallpaper = {
          type = "shader";
          source = ./fixtures/wallpaper-shader.glsl;
        };
        lukshape = "encrypted-root";
        inherit halmasuit-debug halmasuit-luks halmasuit-session
                halmasuit-vm-client nix-config;
        wallpaperStorePaths = [ ./fixtures/wallpaper-shader.glsl ];
      })
    ];
  };

  testScript = ''
    import os
    import sys
    import time

    sys.path.insert(0, "${./lib}")
    os.environ["PATH"] = "${ssimulacra2-cli}/bin:" + os.environ.get("PATH", "")
    os.environ.setdefault("GOLDENS_DIR", "${./goldens}")

    import visual

    def fg_events():
        return [
            e["to"] for e in visual.introspect_events(machine)
            if e["event"] == "foreground_changed"
        ]

    # ── First boot: default config (no LUKS rootfs). ────────────────
    # Plain qcow2 root. We use this window to luksFormat /dev/vdb and
    # switch the bootloader default to the cryptroot specialisation.
    machine.start()
    machine.wait_for_unit("multi-user.target")
    print("PASS: first boot reached multi-user.target")

    # luksFormat /dev/vdb with the canonical passphrase the
    # halmasuit-luks responder will return.
    machine.succeed(
        "printf 'luks-test-unlock-secret' | "
        "cryptsetup luksFormat -q --iter-time 1 /dev/vdb -"
    )
    print("PASS: /dev/vdb formatted with canonical passphrase")
    # Switch the bootloader default to the cryptroot specialisation
    # entry. On the next boot the kernel cmdline will mount
    # /dev/mapper/cryptroot as / via the initramfs unlock path. The
    # specialisation name is generated by systemd-boot from the path
    # `specialisation.cryptroot.configuration` — we list the entries
    # first to learn the exact name (varies with generation prefix).
    entries = machine.succeed("bootctl list --no-pager")
    print("=== bootctl list (default config) ===")
    print(entries)
    import re
    m = re.search(r"id:\s+(\S*cryptroot\S*\.conf)", entries)
    assert m, f"could not find cryptroot specialisation entry:\n{entries}"
    cryptroot_entry = m.group(1)
    machine.succeed(f"bootctl set-default {cryptroot_entry}")
    print(f"PASS: bootctl default → {cryptroot_entry}")
    machine.succeed("sync")

    # ── Crash + reboot into the cryptroot specialisation. ───────────
    machine.crash()
    machine.start()
    machine.wait_for_unit("multi-user.target")
    print("PASS: second boot (cryptroot specialisation) reached multi-user.target")

    # Confirm we're actually rooted on /dev/mapper/cryptroot.
    root_mount = machine.succeed("findmnt -n -o SOURCE /").strip()
    assert root_mount == "/dev/mapper/cryptroot", (
        f"root not on cryptroot mapper: {root_mount}"
    )
    print(f"PASS: / is mounted from {root_mount}")

    # halmasuit-luks's structured log confirms its wire answered the
    # cryptsetup ask-password. Grounds the unlock claim on the agent
    # side, not just the consumer side.
    raw = machine.succeed("journalctl -b --output=cat --no-pager")
    assert "responded to ask-password request" in raw, (
        "halmasuit-luks did NOT log `responded to ask-password request` — "
        "the LUKS unlock may have happened via another agent.\n"
        + machine.execute(
            "journalctl -b -u halmasuit-luks --no-pager | tail -30"
        )[1]
    )
    print("PASS: halmasuit-luks's wire was the unlock responder")

    # ── Post-pivot halmasuit + greeter ───────────────────────────────
    # Wait for the post-pivot setup to complete (greeter_spawned is
    # the last event emitted by run_post_pivot_setup).
    machine.wait_until_succeeds(
        "journalctl -b --output=cat --no-pager "
        "| grep -F '\\\"event\\\":\\\"greeter_spawned\\\"'",
        timeout=60,
    )
    print("PASS: greeter spawned post-pivot")

    # DankGreeter (DMS Quickshell) is the greeter. Wait for its layer
    # surface and the foreground=greeter event so the keyboard arc
    # below has a focused surface to land on.
    machine.wait_until_succeeds(
        "journalctl -b --output=cat --no-pager "
        "| grep -F 'new layer surface'",
        timeout=60,
    )
    machine.wait_until_succeeds(
        "journalctl -b --output=cat --no-pager "
        "| grep -F '\\\"event\\\":\\\"foreground_changed\\\"'",
        timeout=30,
    )
    assert "greeter" in fg_events(), (
        f"expected greeter foreground; got {fg_events()}"
    )
    print("PASS: foreground=greeter; DankGreeter layer surface up")
    # No greeter-scene SSIMULACRA2 golden: DankGreeter renders a live
    # clock (HH:MM) that ticks every minute, and SSIMULACRA2 penalises
    # text-pixel changes heavily — even two captures of the same scene
    # one second apart score far below the global 90.0 threshold,
    # making the gate brittle. The greeter rendering IS still gated
    # visually below via `assert_no_flash_stream` (every frame from
    # initramfs handoff through session_opened passes the pixel-count
    # + non-degenerate stream check) AND the session-scene
    # SSIMULACRA2 golden (niri renders deterministic content). The
    # keyboard arc below additionally proves DankGreeter is alive
    # and focused: typing reaches session_opened iff DankGreeter is
    # talking to halmasuit-greetd.

    # ── R13(b) real keyboard arc through DankGreeter ────────────────
    # Phase B halmasuit argv[0] is rewritten to "@" (RESEARCH.md Phase 2,
    # SurviveFinalKillSignal); pgrep on the binary path doesn't match.
    # Source the PID from the structured `started` event instead — same
    # pattern as tests/full-boot-flash.nix.
    started_events = [e for e in visual.introspect_events(machine) if e["event"] == "started"]
    assert started_events, "halmasuit did not emit `started`"
    halmasuit_pid = str(started_events[-1]["pid"])
    print(f"halmasuit PID = {halmasuit_pid}")

    # DMS QML uses ONE TextField that toggles between username and
    # password mode on Enter. The username→password transition is
    # client-side state inside Quickshell — no journal-visible marker.
    # Same 1-second settle as visual-dankgreeter-auth.nix.
    machine.send_chars("alice")
    machine.send_key("ret")
    time.sleep(1)
    machine.send_chars("testpassword")
    machine.send_key("ret")

    # Real pam_unix → session_opened. halmasuit emits the event as a
    # JSON-escaped entry; grep on the bare token.
    machine.wait_until_succeeds(
        "journalctl -b --output=cat --no-pager | grep -qF session_opened",
        timeout=120,
    )
    print("PASS: session_opened (real pam_unix through broker)")

    # Real niri came up as the broker-launched session.
    machine.wait_until_succeeds("pgrep -x niri", timeout=60)
    # Wait for the swap-gate's session foreground event, not the
    # toplevel-mapped log: those fire one calloop turn apart and racing
    # the introspection JSON dump against `fg_events()` saw only the
    # greeter when the assertion landed between them.
    machine.wait_until_succeeds(
        "journalctl -b --output=cat --no-pager "
        "| grep -F '\\\"event\\\":\\\"foreground_changed\\\",\\\"to\\\":\\\"session\\\"'",
        timeout=60,
    )
    # `fg_events()` runs `journalctl -u halmasuit` without `-b`, so it
    # sees BOTH boots: the crash boot (which reaches foreground=greeter
    # before we crash to land the LUKS header) and the real boot. We
    # check the structural shape: at least one greeter→session
    # transition, and the LAST foreground is `session`.
    events = fg_events()
    assert events and events[-1] == "session", (
        f"final foreground should be session; got {events}"
    )
    assert "greeter" in events[: events.index("session")], (
        f"expected greeter foreground BEFORE session; got {events}"
    )
    print("PASS: niri mapped fullscreen; foreground=session")

    # halmasuit PID continuous across the swap (login-flash invariant).
    # Re-read the `started` event after session_opened; if halmasuit
    # had restarted the unit would emit a NEW `started` with a different
    # pid, breaking the login-flash invariant (kernel-handoff-to-session
    # process continuity). Source from the event stream for the same
    # reason as the initial sample above (argv[0] rewrite blocks pgrep).
    started_now = [e for e in visual.introspect_events(machine) if e["event"] == "started"]
    pid_now = str(started_now[-1]["pid"]) if started_now else ""
    assert pid_now == halmasuit_pid, (
        f"halmasuit restarted across the swap: "
        f"{halmasuit_pid} -> {pid_now}"
    )
    print(f"PASS: halmasuit pid {halmasuit_pid} continuous")

    # Session-scene golden AFTER niri maps.
    time.sleep(2)
    visual.assert_matches_golden(machine, "phase-b-enc-shader-session")
    print("PASS: session-scene golden")

    # ── No-flash invariant over the whole kernel-handoff-to-session ─
    visual.assert_no_flash_stream(machine)
    print("PASS: no-flash invariant over the full Phase B timeline")

    print("visual-phase-b-enc-shader: ALL ASSERTIONS PASSED")
  '';
}
