[package]
name        = "halmasuit"
description = "Linux system compositor (binary)."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[lints]
workspace = true

[dependencies]
halmasuit-introspect = { path = "../halmasuit-introspect", version = "0.1" }
tracing-subscriber.workspace = true
calloop.workspace            = true

[dev-dependencies]
nix        = { workspace = true, features = ["signal"] }
serde_json.workspace = true
